### ISSUE TITLE
Implement missing filters

### ISSUE THREAD

**Issue by johannhof** [cobalt-org/liquid-rust#11]
Feel free to grab any of those and implement! Creating filters is really straightforward, you can find more info [in the README](https://github.com/cobalt-org/liquid-rust#create-your-own-filters) and look at the [existing filters](https://github.com/cobalt-org/liquid-rust/blob/master/src/filters.rs)
- [x] _append_ - append a string e.g. {{ 'foo' | append:'bar' }} #=> 'foobar'
- [x] _capitalize_ - capitalize words in the input sentence
- [x] _ceil_ - 
- [x] _date_ - reformat a date (syntax reference)
- [x] _divided_by_ - integer division e.g. {{ 10 | divided_by:3 }} #=> 3
- [x] _downcase_ - convert an input string to lowercase
- [x] _escape_ - escape a string
- [x] _escape_once_ - returns an escaped version of html without affecting existing escaped entities
- [x] _first_ - get the first element of the passed in array
- [x] _floor_ -
- [x] _join_ - join elements of the array with certain character between them
- [x] _last_ - get the last element of the passed in array
- [x] _map_ - map/collect an array on a given property
- [x] _minus_ - subtraction e.g. {{ 4 | minus:2 }} #=> 2
- [x] _modulo_ - remainder, e.g. {{ 3 | modulo:2 }} #=> 1
- [x] _newline_to_br_ - replace each newline (\n) with html break
- [x] _pluralize_ - return the second word if the input is not 1, otherwise return the first word e.g. {{ 3 | pluralize: 'item', 'items' }} #=> 'items'
- [x] _plus_ - addition e.g. {{ '1' | plus:'1' }} #=> 2, {{ 1 | plus:1 }} #=> 2
- [x] _prepend_ - prepend a string e.g. {{ 'bar' | prepend:'foo' }} #=> 'foobar'
- [x] _remove_first_ - remove the first occurrence e.g. {{ 'barbar' | remove_first:'bar' }} #=> 'bar'
- [x] _remove_ - remove each occurrence e.g. {{ 'foobarfoobar' | remove:'foo' }} #=> 'barbar'
- [x] _replace_first_ - replace the first occurrence e.g. {{ 'barbar' | replace_first:'bar','foo' }} #=> 'foobar'
- [x] _replace_ - replace each occurrence e.g. {{ 'foofoo' | replace:'foo','bar' }} #=> 'barbar'
- [x] _reverse_ - reverse sort the passed in array
- [x] _round_ - rounds input to the nearest integer or specified number of decimals
- [x] _size_ - return the size of an array or string
- [x] _slice_ - slice a string. Takes an offset and length, e.g. {{ "hello" | slice: -3, 3 }} #=> llo
- [x] _sort_ - sort elements of the array
- [x] _split_ - split a string on a matching pattern e.g. {{ "a~b" | split:"~" }} #=> ['a','b']
- [x] _strip_html_ - strip html from string
- [x] _strip_newlines_ - strip all newlines (\n) from string
- [x] _times_ - multiplication e.g {{ 5 | times:4 }} #=> 20
- [x] _truncate_ - truncate a string down to x characters. It also accepts a second parameter that will append to the string e.g. {{ 'foobarfoobar' | truncate: 5, '.' }} #=> 'foob.'
- [x] _truncatewords_ - truncate a string down to x words
- [x] _upcase_ - convert an input string to uppercase
- [x] abs
- [x] compact
- [x] default
- [x] lstrip
- [x] rstrip
- [x] sort_natural
- [x] strip
- [x] uniq

**Comment by fiji-flo** [comment]
missing filters from [liquid](http://shopify.github.io/liquid/):
- [ ] abs
- [ ] compact
- [ ] default
- [ ] lstrip
- [ ] rstrip
- [ ] sort_natural
- [ ] strip
- [ ] uniq

**Comment by johannhof** [comment]
Thanks! I'll add them to the initial list.

**Comment by epage** [comment]
Quick reference to make it easy to finish off the last ones

url_encode
- source: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L44
- test: https://github.com/Shopify/liquid/blob/25c7b05916dd6eae8d824e195e0381a7120f37d5/test/integration/standard_filter_test.rb#L139

url_decode
- source: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L48
- test: https://github.com/Shopify/liquid/blob/25c7b05916dd6eae8d824e195e0381a7120f37d5/test/integration/standard_filter_test.rb#L144

sort_natural
- source: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L140
- test: 
  - https://github.com/Shopify/liquid/blob/64fca66ef5dfd7cf1acef0a7b8cdd825756eb681/test/integration/filter_test.rb#L86
  - https://github.com/Shopify/liquid/blob/25c7b05916dd6eae8d824e195e0381a7120f37d5/test/integration/standard_filter_test.rb#L203

map
- source: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L174
- test: https://github.com/Shopify/liquid/blob/25c7b05916dd6eae8d824e195e0381a7120f37d5/test/integration/standard_filter_test.rb#L242

compact
- source: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L188
- test:
  - https://github.com/Shopify/liquid/blob/64fca66ef5dfd7cf1acef0a7b8cdd825756eb681/test/integration/filter_test.rb#L101
  - https://github.com/Shopify/liquid/blob/25c7b05916dd6eae8d824e195e0381a7120f37d5/test/integration/standard_filter_test.rb#L230

concat
- source: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L227
- concat: https://github.com/Shopify/liquid/blob/25c7b05916dd6eae8d824e195e0381a7120f37d5/test/integration/standard_filter_test.rb#L493
