### ISSUE TITLE
Bug: Array Indexes

### ISSUE THREAD

**Issue by booyaa** [cobalt-org/liquid-rust#127]
liquid-rust version: 0.10.0
rust version: rustc 1.18.0 (03fc9d622 2017-06-06)
OS: macOS Sierra / 10.12.4

```liquid
{% assign tags = "foo,bar" | split: "," %}
tags[0]: {{ tags[0] }}
```
running the code results in

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parser("Expected |, found [")', sr
c/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```liquid
{% for tag in tags %}
   {{ tag }}
{% endfor %}
```

Will build and display each tag. 

I've tested using another liquid [parser](http://harttle.com/shopify-liquid/) and this definitely a problem with liquid-rust.

**Comment by Albibek** [comment]
I've started investigating this issue. Not done yet, but working on it.

Here's what I've found atm:
* https://github.com/Shopify/liquid/wiki/Liquid-for-Designers this doc says they support complex indexing subexpressions like a[0].b["c"]
* Ruby's \w [is not](https://ruby-doc.org/core-1.9.3/Regexp.html#class-Regexp-label-Character+Classes) like in rust, so ".xxx" is parsed as Identifier(".xxx") while it shouldn't.

I think I can fix this eventually.

**Comment by epage** [comment]
That'd be a big help!

I've not been able to set aside time to try to step through the regex based parser.  I'd actually love to switch it to nom or some other parser though it does lose the comparison to shopify's but as you pointed it, it can be misleading.

**Comment by Albibek** [comment]
I think I could look into it in future as well, but after fixing this bug. 
I'd (personally) prefer using https://github.com/Marwes/combine instead of nom.

**Comment by epage** [comment]
I've created #138 to track changing the parser.

I've not explored the parser options, so I'll be deferring to whoever does the work.  It would be helpful if you posted to #138 what your recommendation is and why so that if someone comes along and goes "you did X, why not Y" we have a reason.
