### ISSUE TITLE
Integration tests are not run

### ISSUE THREAD

**Issue by dzamlo** [cobalt-org/liquid-rust#128]
The tests in the `tests` folder are not run.

Because of the `[[test]]` in `Cargo.toml` cargo only run the test specified here. And this test is just an empty file. Because you want to use a non-default feature in a test, this means you cannot just remove this section.

I see multiple ways to solve this issue:

1. Manually specify all the tests in `Cargo.toml`
2. Include all other tests from `liquid.rs` (via `mod`) (this could be done automatically with code generation in `build.rs`)
3. Remove the section from `Cargo.toml` but specify the feature on the command line each time (`cargo test --features "serde"`)

**Comment by epage** [comment]
Thanks! I'm glad the tests still pass even if they haven't been running.  I saw no indication of this behavior in the documentation, and so I opened an issue rust-lang/cargo#4290 about this.

**Comment by epage** [comment]
Oh, and as for a fix, I'm tempted to just to make serde a default feature.
