### ISSUE TITLE
Dot notation form of size not implemented?

### ISSUE THREAD

**Issue by wezm** [cobalt-org/liquid-rust#136]
**liquid-rust version:** 0.10.1
**rust version:** rustc 1.21.0 (3b72af97e 2017-10-09)
**OS:** Arch Linux

I'm using Cobalt (0.7.3) and it appears that the [dot notation form of size](https://shopify.github.io/liquid/filters/size/) doesn't work.

With the following in `index.liquid` and 10 posts:

```
{{ posts | size }}
x
{{ posts.size }}
```
the output is:

```
10
x
```

What I'm trying to do is show some text if there are more than 5 posts:

```
{% if posts.size > 5 %}
  more posts
{% endif %}
```

**Comment by epage** [comment]
Thanks for letting us know about this! I didn't realize some of the filters had a dot-notation form.  It'll be an interesting problem trying to see how to get it to work.

**Comment by epage** [comment]
I forgot, do we have `assign` implemented?  Could that be used as a work around?

```
{% assign posts_size = posts | size %}
{% if posts_size > 5 %}
  more posts
{% endif %}
```

**Comment by epage** [comment]
With some of the API refactorings I'm working on for #95, this might become trivial to implement.  `Value::get` now exists.  When `Value` is an `Array` but someone is doing key-indexing, we can look to see if its `size` and then return the size.

This might be made complicated again by later refactorings for #95 because I'll want to abstract the lookup and make it cheaper in some cases.

**Comment by epage** [comment]
Pieces that need to be touched as part of this
- Modify `Value::get`
- Add `Value::contains`
- Update if tag to use `Value::contains`

The annoyance is that `Value::get` returns a reference but for `size` a new `Value` will need to be returned.  So do we switch to making copies?  Do we make it a `Cow`?

**Comment by epage** [comment]
Looks like we need
- `.size` on Object and Array
- `.first` and `.last` on Array

See https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#allowed-collection-types

**Comment by epage** [comment]
Weird, hashes respond to first but return nothing for last
https://repl.it/repls/ComplicatedVigorousPredictions

**Comment by epage** [comment]
In case it is relevant: https://github.com/Shopify/liquid/blob/master/lib/liquid/variable_lookup.rb
