### ISSUE TITLE
RFC: Use a non-regex parser

### ISSUE THREAD

**Issue by epage** [cobalt-org/liquid-rust#138]
This is a possible enhancement that could make it easier to address some of our bugs and missing features.

The downside is that shopofy/liquid uses regex iirc so it'll be more difficult to follow their grammar.  I have heard that there are some differences in the regex engines that already cause some problems.

### Goals
- Performance (faster than what we have now at least)
- Making it easier to implement features, for example
  - More complex indexing (https://github.com/cobalt-org/liquid-rust/issues/145)
  - Variable includes (https://github.com/cobalt-org/liquid-rust/issues/142)
  - Named arguments for filters (https://github.com/cobalt-org/liquid-rust/issues/92, also requires changes to filter API)
  - nil literals (https://github.com/cobalt-org/liquid-rust/issues/223)
  - blank / empty keywords (https://github.com/cobalt-org/liquid-rust/issues/222)
- Generally easier to maintain
- A concise top-level that reduces churn (all helpers can be moved into a sub-crate and break compat whenever)
- File location information in errors (formerly #232)

### Background

There are really to main issues with the current parser
- The performance of the lexer (I'm assuming thats whats so slow)
- The maintainability of the parser

The parser right now is cobbled together functions that have too much logic in them, causing others to duplicate it.  For example, the for-block has named arguments but not filters, because we don't have reusable argument parsing.  The parser is also inconsistent on how it consumes tokens.  A consistent, composible model would be a big help.

# Solutions

## Patch up the current approach.

The parser could be made more maintainable while keeping the current token stream if desired.  We could make combinators for token processing, that return where they left off parsing (maybe even on failure like nom's IResult).  We can then refactor all of our parsers into using these combinators so we can have an easier to maintain code base.

# Parser comparison

- nom
- [Combine](https://github.com/Marwes/combine)
  - [Author moved on to lalrop](https://www.reddit.com/r/rust/comments/6w6vak/writing_a_pl_in_rust_lalrpop_or_nom_or/dm5ttgh/)
- [Chomp](https://github.com/m4rw3r/chomp)
- pest
- [lalrop](https://github.com/lalrpop/lalrpop)
- [pom](https://github.com/J-F-Liu/pom)

## Benchmarks

- https://github.com/Geal/parser_benchmarks
- https://m4rw3r.github.io/parser-combinator-experiments-rust
- https://m4rw3r.github.io/parser-combinator-experiments-errors
- https://m4rw3r.github.io/parser-combinator-experiments-part-3
- https://m4rw3r.github.io/parser-combinators-road-chomp-0-1
- https://github.com/J-F-Liu/pom

Good
- nom
- pest
- chomp

Bad
- Combine
- pom (order of magnitude slower than pest)

## Line numbers

Good:
- Pest has it native
- Nom has [`nom_locate`](https://github.com/fflorent/nom_locate/blob/master/README.md)

## Composability

Can plugins reuse the grammar without centralizing all token processing which also hurts correctness?

Good:
- Nom

Bad:
- Pest

## Partial parsing

An idea to improve performance and API stability.

Good:
- Nom: slice of str
  - Downside is if you need to store the parse results with what you parsed
- Pest: byte position
  - Good for parse results being in a struct with what was parsed

## Maintenance

Bad
- Chomp hasn't had a commit in over a year

## Brittleness

Bad
- Pest
  - Requires 100% test coverage to ensure grammar changes don't break code. 
  - See https://www.reddit.com/r/rust/comments/9xt5sh/introducing_pest_into_glsl_and_hindsight_about/?st=jooy4jhz&sh=dab05392
  - See https://www.reddit.com/r/rust/comments/9xz9c7/introducing_pest_into_glsl_and_hindsight_about/?st=jooy4k81&sh=39cafabf

## Ergonomics and Docs

Good
- Pest: only thing to complain about is the syntax is less familiar

Mixed
- Nom: bad ergonomics due to the macros but docs are pretty ok

**Comment by epage** [comment]
@gmalette experimented with nom in #137 

> In a previous discussion, you hinted you'd be open to using a parser generator, so I tried to write it in Nom (gmalette#2) but I couldn't generate good error messages.

(from #117)

**Comment by Albibek** [comment]
My biggest concern for [combine](https://github.com/Marwes/combine) here is function/Trait based interface vs nom's macro interface. So the reasnoning mostly falls for macros vs non-macros issues like ease of debugging, learning curve and readability.

Combine was more convenient and to mee it seemed to give less frustration when making a [simple parser](https://github.com/avito-tech/bioyino/blob/master/src/parser.rs) rather than [nom-version](https://github.com/Albibek/brubers/blob/774fe5a090c6582c9ce5a6d6585669008b2917a4/src/parser.rs). This is no doubt very opinionated thing though.

To be more honest, nom has bigger spread over community and in some cases this could be meaningful for contributors to use something that they already know and used before.

There is also a discussion here https://github.com/Marwes/combine/issues/73 that can be useful when making decision.

**Comment by epage** [comment]
I think another thing for us to consider
- Parse errors can report line, column
- Semantic errors can report line, column (which also means a lot of work on our part to preserve it).

We also need to be cognizant of `{raw}` and handle it correctly.  I'm unsure of the trade-offs of making it a built-in or not.

**Comment by gmalette** [comment]
raw and comments in shopify/liquid don't combine right, but I don't think you'll want to be bug compatible for that

**Comment by epage** [comment]
Another good discussion on parsers. The author of combine seems to be endorsing LALROP but it also sounds like it has terrible compile times.

**Comment by gmalette** [comment]
FWIW, I also used rustpeg for [`exceptional`](https://github.com/exceptional-lang/exceptional/blob/master/src/exceptional-grammar.rustpeg), and it was fine, although the syntax is a bit funky.

 In [another project](https://github.com/sgnr/Liquider/blob/5d4ae6dbd9f7740336dfc53100b663899fcae835/lib/liquider/liquid.y), we'd used Racc which is LALR, so LALR-class would be ok.
IIRC the challenge was to generate a parser that could understand custom tags vs block at runtime. In the case of Cobalt/Liquid-rust, would the parser be regenerated?

**Comment by epage** [comment]
If we use nom, this would be helpful: https://github.com/fflorent/nom_locate

**Comment by epage** [comment]
Looks like nom can take in some amount of state.  How much we can "plugin" other parsers, no idea.
https://users.rust-lang.org/t/nom-referencing-external-variables-from-parser-s/21249/5

**Comment by epage** [comment]
Re-openeing because I want to consider this topic some more.
