### ISSUE TITLE
Support 'static str/Cow<str> for Object::insert(...)

### ISSUE THREAD

**Issue by emoon** [cobalt-org/liquid-rust#186]
liquid-rust version: 0.15
rust version: 1.30 (nightly)
OS: macOS 10.13

Hi,

Currently only `String` is supported when doing `Object::insert(name, ...)`. In all my code the inserts could have been using `&'static str` which would have reduced memory allocations quite a bit. I wonder if there are some plans to support that?

**Comment by epage** [comment]
I was just thinking the other day of switching both `Object` keys and `Value` to `Cow`

We can hard code it to `'static` for now but longer term I want to experiment with allowing other lifetimes for cheaper deserialzation.

I am a bit busy on some other projects, so I won't be getting to this too soon but it shouldn't be hard for your to create a PR.

btw what are you using Liquid for?

**Comment by emoon** [comment]
Yeah I thought about `Cow` as well so that might just be fine as well. I think I will do a PR for it with in a few days.

I'm using Liquid for my UI api (Rute) https://github.com/emoon/rute for the code generation phase as it helps keep the code quite a bit cleaner and I'm in the process of moving more code over to it (I notice now that the readme isn't very up to date so I will have to fix that also)

So even if it runs fairly fast right now it will have to generate a fair amount of code so I would like to reduce allocs a bit to speed up the generation.

**Comment by emoon** [comment]
All template parsing is done at the very start for me so parsing performance isn't that important. My critical loop looks something like

**Comment by epage** [comment]
I went ahead and split out my idea in this thread for improving performance, see #188.

With #95, you might be able to get away without even creating the top-level `Object`.

**Comment by epage** [comment]
Fixed by #189
