### ISSUE TITLE
expose Template?

### ISSUE THREAD

**Issue by blaenk** [cobalt-org/liquid-rust#2]
Is there a reason that the `Template` type isn't exposed? The `parse` function returns a value of that type, but we can't annotate values using that type explicitly since it's not a public type. Is this an oversight, or is it deliberate?

**Comment by blaenk** [comment]
The reason I ask is because I wanted to create a map of templates.

**Comment by tailhook** [comment]
+1, I don't think the library is usable without exposing Template.

**Comment by tak1n** [comment]
Sorry for the delay, liquid-rust and cobalt.rs got pretty staled. (got a new ruby job)

Hope https://github.com/cobalt-org/liquid-rust/commit/f893a1be430b3aae5d4aa193b600c65ff2baa481 fixes this.
Feel free to reopen.
