### ISSUE TITLE
Cannot iterate over "object"

### ISSUE THREAD

**Issue by chippers** [cobalt-org/liquid-rust#201]
liquid-rust version: 0.14.3 and 0.15.0 (cobalt v0.12.2 and master)
rust version: rustc 1.29.1 (b801ae664 2018-09-20)
OS: Xubuntu 18.04

Attempting to iterate over an object from data is not possible.  A small reproduction with cobalt is [available here](https://github.com/chippers/cobalt_liquid_iterate_for) with the `cobalt build` output:

```bash
chip@dev:~/temp/cobalt_liquid_iterate_for$ cobalt build
[info] Building from "/home/chip/temp/cobalt_liquid_iterate_for/" into "/home/chip/temp/cobalt_liquid_iterate_for/_site"
Error: build command failed
Caused by: Failed to render content for "index.html"
Caused by: liquid: Expected array, found `object`
from: {% for kv in site.data.authors  %}
```

I'm posting it here instead of the cobalt.rs repo since it seems this library is the root cause of the error.  I tried with the latest release v0.12.2 (liquid-rust 0.14.3) and compiled from source from the master branch (liquid-rust 0.15.0).

I encountered this while [porting the arewewebyet site from Jekyll to Cobalt](https://github.com/bashyHQ/arewewebyet/issues/130), where the authors data file is iterated over once to get a list of curators, and then used elsewhere other times by other templates mostly as an object.

It definitely works in Jekyll, and the [Liquid docs](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#allowed-collection-types) mention the types allowed in for loops.  Here I'm assuming a hash is equivalent to what is called an object here, as it works as expected with Jekyll.

**Comment by epage** [comment]
Thanks for reporting this!

I'll try to get to this tonight to unblock you.

btw that liquid document is a **lot** better than the [one I've been using](https://shopify.github.io/liquid/tags/iteration/).  I'll need to audit liquid-rust against that.

**Comment by chippers** [comment]
It's the one in the readme 😃 

https://github.com/cobalt-org/liquid-rust/blame/e553f8ac37d76d1670a84241ad0cd954cec593c2/README.md#L44

**Comment by epage** [comment]
Thats what I get for using google rather than our own readme :)
