### ISSUE TITLE
Unable to use a variable or value index for object in assign tag

### ISSUE THREAD

**Issue by chippers** [cobalt-org/liquid-rust#207]
liquid-rust version: 0.16.0
rust version: 1.29.1
OS: Xubuntu 18.04

Hi again, and thanks for such a rapid fix yesterday.

Here, we are unable to use a value as an index to an object in an assign tag.  [I've updated the small testable case from yesterday as an example](https://github.com/chippers/testing_liquid-rust_and_cobalt.rs/blob/2dcdcb77bd5d26c1c2a00cc1fe4209c88a07932f/index.md).

```
{% for kv in site.data.authors %}
{% assign name = kv[1].name %}
* {{ kv[0] }}: {{ name }}
{% endfor %}
```

The failure is in assign, it works when `kv[1].name` is directly used.  (what is the name of the `{{ }}` blocks?)

This is used quite a lot in arewewebyet, and many Jekyll project's I've written/read make use of this feature to shorthand variables that are otherwise unwieldy.  It's possible to not use it, but this feature makes reading the code a lot easier.

I took a quick look at perhaps implementing the fix myself, but after a small bit of reading it seems like the fix would likely be relatively invasive for a codebase I am not familiar with yet.  Here's some of the things I found that might help:

* It seems that parsing the assign tag's arguments goes wrong when [parsing into a `FilterChain`]
* [`fn parse_output`] expects there to only be a single `Token` of input to turn into an `Argument`
* The lexer outputs `[Identifier("kv"), OpenSquare, IntegerLiteral(1), CloseSquare, Dot, Identifier("name")]` for the input `kv[1].name`
* In the library that Jekyll uses, [`liquid-c`], the parser has a special case for `Token::OpenSquare` in [`parse_expression`] and [`parse_variable`].  It also has a special case for `Token::Dot`, but in `liquid-rust` the dots are already handled and put inside a single identifier - like `Identifier("site.data.authors")`.

Hopefully some of that is helpful, again not yet familiar with the codebase.

Thanks

[parsing into a `FilterChain`]: https://github.com/cobalt-org/liquid-rust/blob/master/src/tags/assign_tag.rs#L46
[`fn parse_output`]: https://github.com/cobalt-org/liquid-rust/blob/master/liquid-compiler/src/parser.rs#L123
[`liquid-c`]: https://github.com/Shopify/liquid-c
[`parse_variable`]: https://github.com/Shopify/liquid-c/blob/master/ext/liquid_c/parser.c#L87
[`parse_expression`]: https://github.com/Shopify/liquid-c/blob/master/ext/liquid_c/parser.c#L131

**Comment by epage** [comment]
Yeah, the parser is in terrible shape and gets in the way of conforming (e.g. https://github.com/cobalt-org/liquid-rust/issues/92, https://github.com/cobalt-org/liquid-rust/issues/145).  I'd rather rewrite it (https://github.com/cobalt-org/liquid-rust/issues/138) but just haven't gotten to it yet.

I'll take a look to see what I can do.

**Comment by epage** [comment]
I actually got something to work! Going to bed soon, it'll probably be tomorrow morning before I finish the merges and get the releases out

**Comment by epage** [comment]
New cobalt release is now out!
