### ISSUE TITLE
Cannot use Identifier as object index

### ISSUE THREAD

**Issue by chippers** [cobalt-org/liquid-rust#209]
liquid-rust version: 0.16.1 (cobalt 0.13.2)
rust version: 1.29.1
OS: Xubuntu 18.04

Hi again!

It's currently not possible to use an identifier as an object index.  This is useful for when you have a post with an author slug in the frontmatter data, and have all author data in another data file.  Below is a small test case (although a bit useless in this specific test)

```
{% for kv in site.data.authors %}
{% assign key = kv[0] %}
* {{ site.data.authors[key] }}: {{ site.data.authors[key].name }}
{% endfor %}
```

Cobalt v0.13.2 will spit out:
```
Error: build command failed
Caused by: Failed to render content for "index.html"
Caused by: liquid: Expected string | whole number, found `[`
from: {% for kv in site.data.authors  %}
```

Look like this comes from https://github.com/cobalt-org/liquid-rust/blob/master/liquid-compiler/src/parser.rs#L96 , but I don't know how the previous patch to allow multiple tokens for identifiers will work with it, as it also has token amounts hardcoded.

**Comment by epage** [comment]
btw this is a dup of https://github.com/cobalt-org/liquid-rust/issues/145

**Comment by epage** [comment]
Granted, it might be easier to implement a subset (just an identifier) of #145 (unsure how complex the expressions can get) so if thats all thats needed, I might be able to get this implemented without the new parser.

**Comment by chippers** [comment]
ah i did not read the current issues carefully enough

Yeah, as far as I can see the current codebase only uses things like `{% assign author = site.data.authors[page.data.source.author] %}` so that should be good enough for now

**Comment by epage** [comment]
Finally got #214 up.

**Comment by epage** [comment]
liquid 0.17.0 is publishing right now.  I'll have to get to updating cobalt tomorrow.

**Comment by epage** [comment]
@chippers I just wanted to check in since it has been a while since I've heard anything.  How are cobalt / liquid treating you?
