### ISSUE TITLE
Implement missing tags

### ISSUE THREAD

**Issue by tak1n** [cobalt-org/liquid-rust#21]
https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#tags

- [x] assign - Assigns some value to a variable
- [x] capture - Block tag that captures text into a variable
- [x] case - Block tag, its the standard case...when block
- [x] comment - Block tag, comments out the text in the block
- [x] cycle - Cycle is usually used within a loop to alternate between values, like colors or DOM classes.
- [x] for - For loop
- [x] break - Exits a for loop
- [x] continue Skips the remaining code in the current for loop and continues with the next loop
- [x] if - Standard if/else block
- [x] include - Includes another template; useful for partials
- [x] raw - temporarily disable tag processing to avoid syntax conflicts.
- [x] unless - Mirror of if statement

**Comment by tcsc** [comment]
Any suggestions of which would be the most useful to attack? I've got a few ideas on how to approach `cycle`, and figuring out a sane way to do `break` or `continue` would be ... interesting.

PS: I also have an implementation of `capture` that will be ready for review once some other stuff passes review.

**Comment by tak1n** [comment]
@tcsc the most useful one is the one which was requested on cobalt.rs: https://github.com/cobalt-org/cobalt.rs/issues/61.
But we should implement all of them in future.

Maybe you can work together with @LucioFranco who is also interested in implementing the include tag.

Regarding to your pull request, I still have to get comfortable with liquid-rust therefore @johannhof is in charge for merging and reviewing pull requests for liquid-rust. :)

**Comment by tcsc** [comment]
No worries. A naïve implementation of `include` should be pretty straightforward. 

It does present the opportunity for a pretty large security hole, though. I mean what if someone were to `{% include /root/.ssh/id_rsa %}.`... Oops. Might be worth seeing if shopify does anything special. Will have a peek.

**Comment by tcsc** [comment]
...and I didn't mean the bit about the pullreq to be naggy. It was just a heads up, so someone  didn't write the same code twice. Apologies if it came off whiney. :-)

**Comment by tak1n** [comment]
@tcsc yep we should see how liquid from shopify is handling that cases.

Also it didn't came off whiney or naggy at all, just wanted to give you some feedback as of why I'm not dealing with your PR's.

We appreciate you're contributions thanks :smile:

**Comment by johannhof** [comment]
> Apologies if it came off whiney

Didn't seem that way at all. :)

Regarding the `include` tag: since it's part of the "standard" we should include it, but I'd also love to write a plugin that enables things like mixins or importing JSON/Yaml data into the context.

Regarding Cobalt, I would also like to move away from Cobalt handling the include/inheritance stuff (it's pretty ugly right now anyway) and just delegate that to liquid inside Cobalt.

**Comment by johannhof** [comment]
@tcsc: considering @LucioFranco is interested in trying `include`, I think `break`, `continue` or `cycle` sound like great choices for you! You're probably more familiar with the loop code than me right now. :sweat_smile:. And it does sounds really interesting.

Thanks again :)

**Comment by johannhof** [comment]
`unless` sounds like a good first bug to me, the major difficulty should be how to avoid code duplication with `if`

**Comment by LucioFranco** [comment]
I will take a crack at `include` today! Thanks for the info @johannhof

**Comment by johannhof** [comment]
Done 🎉

**Comment by johannhof** [comment]
Thanks so much @tcsc for implementing all these tags. The code is looking great and I hope you had fun implementing it!

**Comment by johannhof** [comment]
Also thank you to @LucioFranco for `include` of course :)
