### ISSUE TITLE
`sort` and `sort_natural` should supporting Objects and by a specific field

### ISSUE THREAD

**Issue by epage** [cobalt-org/liquid-rust#249]
Example test
```rust
    let assigns = v!({
        "words": ["case", "Assert", "Insensitive"],
        "hashes": [{ "a": "A" }, { "a": "b" }, { "a": "C" }],
    });

    // Test hashes
    assert_template_result!(
        "A b C",
        "{{hashes | sort_natural: 'a' | map: 'a' | join}}",
        assigns
    );
```

- [Rust implementation](https://github.com/cobalt-org/liquid-rust/blob/master/src/filters/mod.rs)
- [Ruby implementation](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb)
- [Relevant tests](https://github.com/cobalt-org/liquid-rust/search?q=liquid+249&unscoped_q=liquid+249)
  - Once this is working, ideally the test will start failing.  We would just need to remove the `#[should_panic]` on it
  - If the test doesn't start failing, please temporarily remove `#[should_panic]`, and find or create an issue for the new failure

**Comment by limeschool** [comment]
Encountered this today while working on my blog, attempting to sort by a post's `date.year` value (sorting is only working on a top-level value, like `date` itself)

**Comment by epage** [comment]
@limeschool looks like this issue was addressed in be2b2354aca6342a4b57b0b5be4966204fc92cba (released in 0.20.0) but it never got closed.  

Where is it you are using liquid that you ran into this?  Cobalt?  I believe that upgraded to 0.20.0 in the 0.16.0 release.

**Comment by limeschool** [comment]
@epage I am using Liquid in [my own project](https://github.com/Dirout/dokkoo), a program which can be used as a static site generator, to output [my blog](https://github.com/Dirout/blog).
In [a file in my blog](https://github.com/Dirout/blog/blob/master/layouts/home.mokkf), you can see the following Liquid code:
```liquid
{% assign posts_by_date = collections["posts"] | sort: "url" %}
{%- for post in posts_by_date reversed -%}
…
{%- endfor -%}
```

The `post` object, in this case, is structured in [a specific manner](https://dirout.github.io/dokkoo/dokkoo/struct.Page.html).
I am attempting to sort by `{{ `[`post`](https://dirout.github.io/dokkoo/dokkoo/struct.Page.html)`.`[`date`](https://dirout.github.io/dokkoo/dokkoo/struct.Date.html)`.`[`rfc_3339`](https://dirout.github.io/dokkoo/dokkoo/struct.Date.html#structfield.rfc_3339)` }}`, a value which exists—but, I can only sort by top-level values, such as `{{ post.date }}` itself (which Liquid interprets as just a garbled string formed by a concatenation of all the data in [the `date` structure](https://dirout.github.io/dokkoo/dokkoo/struct.Date.html)), or `{{ post.url }}`; this is the bug, and from what I can tell, the Ruby implementation of Liquid does allow this, so this should be possible in this Rust implementation of the language.

**Comment by epage** [comment]
Oh, sorry, I missed that this was for nested properties.

Looking at [the ruby](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L154), they are just doing `a[property]`, so unless they are doing something specially internally to `a`, they don't support nesting.

I tried to create [a reproduction case](https://repl.it/join/azwajdlo-epage) and if I did it right, it confirms that the ruby version is treating it as `a["date.year"]` instead of `a["date"]["year"]`.

The output of
```ruby
require "liquid"

@template = Liquid::Template.parse('
dotted {{data[0].date.year}}
quoted {{data[0]["date"]["year"]}}
hybrid {{data[0]["date.year"]}}

{{data | sort: "date.year"}}
')
output = @template.render(
  'foo' => 'bar',
  'data' => [
    {
      "date" => {
        "month" => 3,
        "year" => 2019,
      },
    },
    {
      "data" => {
        "month" => 2,
        "year" => 2018
      },
    },
    {
      "data" => {
        "month" => 4,
        "year" => 2020
      },
    },
  ]
) 
puts output
```

was
```
{"data"=>{"month"=>4, "year"=>2020}}{"data"=>{"month"=>2, "year"=>2018}}{"date"=>{"month"=>3, "year"=>2019}}
```

**Comment by limeschool** [comment]
So, if I'm understanding right, being able to sort by a nested property is not possible in standard Liquid?
I found [this tutorial](https://www.siteleaf.com/blog/advanced-liquid-sort/) from a Jekyll-powered CMS which sorts by properties like `meta.sticky` and `meta.num`. Could this be specific to Jekyll's flavour of Liquid?
Could there be a way for me to work around this, or am I just unable to sort this way?
Thanks

**Comment by limeschool** [comment]
For my specific situation, I've found an absurd workaround.
Here's a reminder of what I'm dealing with:
- `collections["posts"]`
  - `post`
    - `post.date`
      - `post.date.rfc_3339`

I'm simply trying to sort `collections["posts"]` by that `rfc_3339` value. Here's what I came up with:
```liquid
{% assign urls = '' | split: '' %}
{% assign post_date_rfc_3339 = collections["posts"] | map: 'date' | sort: "rfc_3339" %}
{%- for post_date in post_date_rfc_3339 reversed -%}
  {%- for post in collections["posts"] -%}
    {% if post.date.rfc_3339 == post_date.rfc_3339 %}
      {% unless urls contains post.url %}
        {% assign urls = urls | push: post.url %}
          …
      {% endunless %}
    {% endif %}
  {%- endfor -%}
{%- endfor -%}
```

This is equivalent to what I was expecting would work:
```liquid
{% assign posts_by_date = collections["posts"] | sort: "date.rfc_3339" %}
{%- for post in posts_by_date reversed -%}
  …
{%- endfor -%}
```

That's the best I've come up with to solve this.

**Comment by epage** [comment]
Looks like it is a Jekyll extension
- https://jekyllrb.com/docs/liquid/filters/
- https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L297
And to be clear, we are fine in supporting those.  iirc they have to manually be added but can be found in `liquid-lib`.

**Comment by epage** [comment]
btw our tracking issue for Jekyll is https://github.com/cobalt-org/liquid-rust/issues/311.  We can open a more specific one if you want.

Closing this out since we support standard liquid.

**Comment by epage** [comment]
@limeschool in case github is being weird with tagging, I've started implementing this over in #438.  Right now its just a skeleton of an implementation with only a fraction of the tests ported over but ran out of time tonight.
