### ISSUE TITLE
`raw` block doesn't ignore enough

### ISSUE THREAD

**Issue by epage** [cobalt-org/liquid-rust#277]
Example test
```rust
    assert_template_result!(
        " Foobar {% invalid ",
        "{% raw %} Foobar {% invalid {% endraw %}",
    );
```

Possibly related to #227

**Comment by epage** [comment]
Just ran into this with the following:

```
{% raw %}
Standard include: {% include variable %}
Jekyll-style include: {% include {{ variable }} %}
{% endraw %}
```

produced
```
Error: Failed to render content for "news/2020/03/liquid-in-2018/index.html"
Caused by: liquid:   --> 28:34
   |
28 | Jekyll-style include: {% include {{ variable }} %}␊
   |                                  ^---
   |
   = expected Value, Range, ">", "<", "=", ",", ":", "==", "!=", "<>", ">=", or "<="
```

**Comment by Goncalerta** [comment]
> Just ran into this with the following:
> 
> ```
> {% raw %}
> Standard include: {% include variable %}
> Jekyll-style include: {% include {{ variable }} %}
> {% endraw %}
> ```
> produced
> 
> ```
> Error: Failed to render content for "news/2020/03/liquid-in-2018/index.html"
> Caused by: liquid:   --> 28:34
>    |
> 28 | Jekyll-style include: {% include {{ variable }} %}␊
>    |                                  ^---
>    |
>    = expected Value, Range, ">", "<", "=", ",", ":", "==", "!=", "<>", ">=", or "<="
> ```

This specific error can be solved by adding `Expression` as a possible `TagToken` in the `grammar.pest`. This is assuming that you intend to add `{{ variable }}` as a `TagToken` (which will be necessary in order to implement jekyll-style includes).

**Comment by epage** [comment]
That would work around this specific case but I suspect `raw` should allow invalid liquid.

#309 is to track adding support for Jekyll-style includes.

**Comment by Goncalerta** [comment]
Regarding  `test_open_tag_in_raw()` in `tests\conformance_ruby\tags\raw_tag_test.rs`, line 41:
```
    assert_template_result!(
        " test {% raw %} {% endraw %}",
        "{% raw %} test {% raw %} {% {% endraw %}endraw %}",
    );
``` 
This was a mistype, right? It was supposed to be:
```
    assert_template_result!(
        " test {% raw %} {% endraw %}",
        "{% raw %} test {% raw %} {% endraw %}{%endraw %}",
    );
``` 
I just want to be sure, though I doubt ruby liquid would allow such syntax.

**Comment by Goncalerta** [comment]
I just looked it up and [this is indeed the same test as ruby](https://github.com/Shopify/liquid/blob/master/test/integration/tags/raw_tag_test.rb).

I still want to believe this is a mistake and by coincidence ruby liquid actually worked. I can't see how that input would be supposed to return the output like that.

On the same note, there is `tests\conformance_ruby\tags\standard_tag_test.rs`, `test_has_a_block_which_does_nothing()`, line 42:
```
assert_template_result!("", "{% comment %}{% raw %} {{%%%%}}  }} { {% endcomment %} {% comment {% endraw %} {% endcomment %}");
```
I suggest changing that into:
```
{% comment %}{% raw %} {{%%%%}}  }} { {% endcomment %}{% comment %}{% endraw %} {% endcomment %}
```
Because otherwise the comment will be closed in the middle of the input, and another (unpaired) `{% endcomment %}` will appear at the end, after many invalid tokens. How can that return an empty string when the comment ends midway? I guess this is the result of some weird buggy sinergy between `comment` and `raw` in ruby liquid.

**Comment by epage** [comment]
> I just looked it up and this is indeed the same test as ruby.

You can actually trace each tests history back to the ruby all in-tree.  I committed the ruby files and over several commits morphed them into what they are now.

https://github.com/cobalt-org/liquid-rust/commits/master/tests/conformance_ruby/tags/raw_tag_test.rs

> I still want to believe this is a mistake and by coincidence ruby liquid actually worked. I can't see how that input would be supposed to return the output like that.

On the other hand, how would you document `{% raw %}` without being able to do that?

> I suggest changing that into:

Except we want to keep these tests the same as the Ruby version to ensure compliance.

**Comment by Goncalerta** [comment]
> On the other hand, how would you document `{% raw %}` without being able to do that?

How is raw documented in order to allow that? I don't even understand what's going on to end up with that result. Am I missing a key feature?
