### ISSUE TITLE
Implement where filter

### ISSUE THREAD

**Issue by epage** [cobalt-org/liquid-rust#291]
Example test:
```rust
    assert_eq!([{ v!("a"): v!("ok") }], filters!(where, { v!("a"): v!("ok") }, "a", r#"ok")#);
```

- [Where filters live](https://github.com/cobalt-org/liquid-rust/blob/master/src/filters/mod.rs)
- [Ruby implementation](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb)
- [Relevant tests](https://github.com/cobalt-org/liquid-rust/search?q=liquid+291&unscoped_q=liquid+291)
  - Once this is working, ideally the test will start failing.  We would just need to remove the `#[should_panic]` on it
  - If the test doesn't start failing, please temporarily remove `#[should_panic]`, and find or create an issue for the new failure

**Comment by or17191** [comment]
I've opened a PR for this issue (https://github.com/cobalt-org/liquid-rust/pull/349)
