### ISSUE TITLE
be multithread-friendly?

### ISSUE THREAD

**Issue by blaenk** [cobalt-org/liquid-rust#3]
I wanted to parse many templates into `Template`s and store them in an `Arc<Mutex<HashMap<String, Template>>>` so that multiple threads could access the template to render various `Context`s, to avoid re-parsing a given template each time it needs to be rendered. However, many things seem to be tangled up in local, non-`'static` references, which means that I can't simply specify `Template<'static>` or `Box<Renderable + Sync + Send + 'static>`. The parser in particular seems to revolve entirely around local references.

Would you guys be open to creating a template type that is "self-contained," so that it is implicitly `Sync + Send + 'static`, to allow us to send and share them between threads? I can do this with the `handlebars` crate, for example, because the [`Template`](http://sunng.info/handlebars-rust/handlebars/struct.Template.html) type is like this. They also have a [`Registry`](http://sunng.info/handlebars-rust/handlebars/struct.Handlebars.html) type that makes it very easy to render a given template "by name," so I simply stick this type in an `Arc<Mutex` after I parse my templates and then various threads can use it to render separate documents.

The only alternative I have now, that I can think of, is to re-parse every template at the time and context that it needs to be rendered, which is a shame.

**Comment by tak1n** [comment]
I'm currently in process of learning rust properly, so no Idea what exactly todo here :smile: .
Feel free to open a PR or wait until I grasp it properly and can change it.

Thx for opening and making some concurrency suggestions

**Comment by Albibek** [comment]
Hi. 
The only thing to do here, as I see it, is requiring Renderable to be Sync+Send. 
Here's an example with tests: https://github.com/Albibek/liquid-rust/commit/a550dc8af51d74abebc86700e6ad3558ebd6843d

**Comment by johannhof** [comment]
Hm that seems reasonable. @Albibek mind making a PR?

**Comment by epage** [comment]
@blaenk  did merging of #63 solve your needs or is there something more?

**Comment by blaenk** [comment]
Although I'm not able to check right now, that does look like it should work. Thanks @Albibek !
