### ISSUE TITLE
Error with double curly brackets "}}" inside code blocks in cobalt 0.15.0

### ISSUE THREAD

**Issue by uwearzt** [cobalt-org/liquid-rust#320]
Starting with 0.15.0 i get an error message

```
Error: build command failed
Caused by: Failed to render content for "posts/2011/03/04/sending-apple-push-notifications-with-erlang.html"
Caused by: liquid:    --> 100:27
    |
100 | "{"aps":{"alert":"Message"}}"␊
    |                           ^---
    |
    = expected EOI, Tag, Expression, or Raw
```

 from the code blob:

```
```erlang
2> pushnotification:send("Message").
"{"aps":{"alert":"Message"}}"
```

this works perfectly fine:

```
```erlang
2> pushnotification:send("Message").
"{"aps":{"alert":"Message"} }"
```

i guess the content inside a code block should be completely ignored by cobalt / liquid.

**Comment by Geobert** [comment]
I've encountered this, and `{% raw %}` nor `{% highlight %}` help :-/

**Comment by Geobert** [comment]
It seems that `{% raw %}` is not working at all

**Comment by epage** [comment]
Liquid has been published.  I've got a PR out to update cobalt and will then release.
https://github.com/cobalt-org/cobalt.rs/pull/590
