### ISSUE TITLE
Delete gh-pages branch

### ISSUE THREAD

**Issue by Goncalerta** [cobalt-org/liquid-rust#329]
I've been wondering why the gh-pages branch is still on. It wasn't updated in the last 2 years and, if I'm understanding correctly, it would be supposed to host the documentation for liquid (which is nowadays done with docs.rs).

Not that it actually makes a big difference that it is there or not, but I think that branch is doing nothing there and could just be removed.

**Comment by epage** [comment]
Thanks, I had lost track of that being there.
