### ISSUE TITLE
Borrow `self` in `parse_file`

### ISSUE THREAD

**Issue by nic-hartley** [cobalt-org/liquid-rust#345]
liquid-rust version: 0.19.0 (but [still present on master](https://github.com/cobalt-org/liquid-rust/blob/master/src/parser.rs#L287))  
rust version: 1.36.0  

[`Parser.parse_file`](https://docs.rs/liquid/0.19.0/liquid/struct.Parser.html#method.parse_file) takes `self` instead of `&self`. This is directly counter to how `parse` works, and prevents you from reusing the same parser with multiple files without manually rewriting the code in `parse_file`. It's unnecessary, as far as I can tell; `self` is only used to call `parse`, which borrows.

**Comment by epage** [comment]
Yup, thats bad.  We'll need to fix that.

**Comment by nic-hartley** [comment]
@epage On the plus side, it's only two characters to change the actual code, and all but the most esoteric uses (e.g. passing it as a function pointer) should work with no or few changes to source code. e.g. if something calls `parser.parse_file`, that works whether `parse_file` owns or borrows `parser` -- it just changes whether it's usable after the fact.
