### ISSUE TITLE
Include with block

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/liquid-rust#36]
@jespino suggested

> Currently the layouts are on liquid have to been rewritten various times when you want to define different layouts. Could be nice to have a "extends" tag like in django templates or jinja. or something that allow to build a template from a base template.

base.liquid

``` liquid
<html>
  <body>
    {{include_block}}
  </body>
</html>
```

default.liquid

``` liquid
{% include "base.liquid" block_var="include_block" %}
  <h1>Posts</h1>
  <div>{{ content }}</div>
{% endinclude %}
```

It might be better to do something like `{% include "base.liquid" with include_block %}`.

**Comment by epage** [comment]
This is split into #143 and #237
