### ISSUE TITLE
[Question/Feat Req] Query for links in the template?

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/liquid-rust#362]
Hi, 

Is there a way to get the links present in the template?

I'm looking for a way to manage links checking in Antimoine (would be usefull for Cobalt as well) and was wondering if I need to parse the content myself or rely on Liquid for this :)

**Comment by Geobert** [comment]
Ok, forget this, it's not liquid's job, it's cmark's ^^'

**Comment by epage** [comment]
Yes, the options are
- Do this via markdown
- Generalize it and parse HTML
- Write a liquid tag for links

My plan is to do it with markdown.
