### ISSUE TITLE
Assign does not support piped expressions

### ISSUE THREAD

**Issue by bacoboy** [cobalt-org/liquid-rust#40]
So I started working on an implmentation of `split` [here](https://github.com/bacoboy/liquid-rust/commit/3fdc801af325b9ca0cec64abd9f338c2181dac19).

The unit test passes just fine, but the resulting `Array` causes a problem downstream as you can see from the failed test:
```
---- split stdout ----
	thread 'split' panicked at 'called `Result::unwrap()` on an `Err` value: Lexer("\' is not a valid identifier")', src/libcore/result.rs:746
stack backtrace:
   1:        0x10bd959f8 - std::sys::backtrace::tracing::imp::write::hf68f1a220b61702c
   2:        0x10bd97c95 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hb638acea7c29901b
   3:        0x10bd9781f - std::panicking::default_hook::h508c3dab3df347d6
   4:        0x10bd8c4d6 - std::sys_common::unwind::begin_unwind_inner::h17f9e42de6d55309
   5:        0x10bd8d28e - std::sys_common::unwind::begin_unwind_fmt::h039d18bd8498e1d0
   6:        0x10bd94cc7 - rust_begin_unwind
   7:        0x10bdbe510 - core::panicking::panic_fmt::h813eaa27a5810609
   8:        0x10bbc1ee8 - core::result::unwrap_failed::he9d1212db5110052
   9:        0x10bbc1828 - _<std..result..Result<T, E>>::unwrap::h7493e55a0acc9844
  10:        0x10bbcafcb - filters::split::h885acea6ebf1f10e
  11:        0x10bbe82cb - _<F as std..boxed..FnBox<A>>::call_box::h48dd10267ee7767d
  12:        0x10bbea79d - std::sys_common::unwind::try::try_fn::hc72e80a3e6bb322c
  13:        0x10bd94c5b - __rust_try
  14:        0x10bd94be3 - std::sys_common::unwind::inner_try::h74a189ca1fbe8e07
  15:        0x10bbeab84 - _<F as std..boxed..FnBox<A>>::call_box::h8f9b07ad31279db5
  16:        0x10bd96ee8 - std::sys::thread::Thread::new::thread_start::h40a33956f4cb7596
  17:     0x7fff9be2899c - _pthread_body
  18:     0x7fff9be28919 - _pthread_start
```
Since there are no other implementations of filters that return `Value::Array`, this may have just been overlooked in the filter scaffolding...  Need some help here.  Thanks!

**Comment by johannhof** [comment]
Hey, thanks for helping out!

Mmh, that doesn't look like it comes from returning an Array. You can only get that error from lexer::tokenize, which is called in `parse`. I'll try check out your patch and play around with it. My first guess is that the fixture string at the bottom is lexed incorrectly.

**Comment by bacoboy** [comment]
Yea, I wasn't sure what that stacktrace was telling me, but figured the code should give you a good lead.  Let me know what you find out!

**Comment by johannhof** [comment]
So, this seems to be a problem with the `assign` tag that does not allow for piping and accepts only single values or variables as rhs elements. I should get around fixing that soon. However, I would recommend just leaving that particular test case out for now (the one in `tests/filters.rs`). There's nothing wrong with your solution and the array should work fine :)

Thanks! Looking forward to your PR!

**Comment by bacoboy** [comment]
You sure you want the PR on this before your fix (so I can test it all together)?

**Comment by bacoboy** [comment]
Thanks for the fix.  This fixes splits on non-comma, etc which I think is being tracked in #41.  So I'll make a PR with a simple test which passes, but will need to recheck when the comma fix is in.
