### ISSUE TITLE
Date filter does not work

### ISSUE THREAD

**Issue by PhilippeAssis** [cobalt-org/liquid-rust#405]
liquid-rust version: Branch master (0.20.0 ???)
rust version: rustc 1.42.0 (b8cedc004 2020-03-09)
OS: Ubuntu 18.04

I'm trying to use the "date" filter. But he has not lived up to expectations.
When I use a template reading using "now" as a parameter for "date", I get the expected return.
But when I use a date as a parameter for the "date" it returns the parameter to me without any type of typing.

Example:
```
{{"now" | date: "% Y-% m-% d% H:% M"}} \\ should be 2019-09-19 17:48
2019-09-19 17:48 \\ Good!

{{"March 14, 2016" | date: "% b% d,% y"}} \\ should be Mar 14, 16
March 14, 2016 \\ Bad!
```
I noticed that the tests do not cover these cases, testing only cases of invalid parameters.

```rust
fn test_date_raises_nothing() {
    assert_template_result!("", r#"{{ "" | date: "%D" }}"#);
    assert_template_result!("abc", r#"{{ "abc" | date: "%D" }}"#);
}
```

**Comment by epage** [comment]
As of right now, we only support limited date formats.  Adding more formats is tracked with https://github.com/cobalt-org/liquid-rust/issues/48
