### ISSUE TITLE
date filter will panic on invalid format string

### ISSUE THREAD

**Issue by fasterthanlime** [cobalt-org/liquid-rust#409]
liquid-rust version: 0.20.1
rust version: 1.44.0
OS: Linux

See this playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=54a0544244f248603e84abb30c05c0b6

Input like that:

```html
      <p>
        Date {{ row.date | date: "%Y %h %8" }}
      </p>
```

will currently make the stdlib's `date` filter panic.

Not a huge deal as that filter can be overriden with a custom implementation, but still probably should not panic out of the box

**Comment by fasterthanlime** [comment]
Until chrono allows validating a format string, a quick workaround might simply be to wrap the result of `chrono::DateTime::format` in a safe wrapper, like so:

```rust
use chrono;
use std::fmt;

fn main() {
    let now = chrono::Utc::now();
    let now = SafeFormat(now.format("%Y %h %8")).to_string();
    println!("We're in {}", now);
}

struct SafeFormat<T>(T)
where
    T: fmt::Display;

impl<T> fmt::Display for SafeFormat<T>
where
    T: fmt::Display,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.0.fmt(f) {
            Err(e) => write!(f, "[error: {}]", e)?,
            _ => {}
        }
        Ok(())
    }
}
```

**Comment by epage** [comment]
Thanks for reporting this! I've taken a slightly different approach for solving it to help ensure people see errors.

**Comment by epage** [comment]
liquid-lib v0.20.2 is now published with this fix

**Comment by fasterthanlime** [comment]
> I've taken a slightly different approach for solving it to help ensure people see errors.

That is a much better fix. Thanks a lot!
