### ISSUE TITLE
Filter arguments can not contain spaces and commas (and possibly some other chars)

### ISSUE THREAD

**Issue by kstep** [cobalt-org/liquid-rust#41]
I try to compile the following liquid template:

```liquid
{{ title | replace:"hello world","hello, world" }}
```

I get the following error:

```text
Liquid error: Parsing error: parse_output: Identifier("\"hello") not implemented
```

When I remove spaces and leave out comma:

```liquid
{{ title | replace:"helloworld","hello,world" }}
```

I get the same error.

When I remove both spaces and comma:

```text
{{ title | replace:"helloworld","helloWorld" }}
```

I get my example compiled.

It seems like filter arguments parser doesn't parse strings in quotes correctly.
I also tried to replace double quotes with single quotes to no avail.

**Comment by johannhof** [comment]
Thanks for reporting, I'll try to fix this soon!
