### ISSUE TITLE
Add support for `where` filter

### ISSUE THREAD

**Issue by epage** [cobalt-org/liquid-rust#418]
This was in #311 but as of Liquid 4.0.2 it is now in liquid's stdlib.

**Comment by epage** [comment]
https://github.com/Shopify/liquid/blob/master/History.md#402--2019-03-08

**Comment by dillonfagan** [comment]
Thanks for adding this!

**Comment by epage** [comment]
Good news.  Someone contributed `where` but we overlooked getting it added by default.
