### ISSUE TITLE
Correct path for partials

### ISSUE THREAD

**Issue by stevensonmt** [cobalt-org/liquid-rust#444]
liquid-rust version: 0.22
rust version: 1.52.1
OS: Arch Linux

Can't figure out the directory structure needed to use partial templates. I've tried the implicit convention suggested by Shopify (template in `templates` dir, snippets in sibling `snippets` dir, calling include with just the partial name rather than filename). I've tried relative paths with the full filename. I've tried absolute paths with the full filename. None have worked and I'm not sure why.

**Comment by epage** [comment]
We refer to them as "partials" and you need to set your [`PartialCompiler` on the `LiquidBuilder`](https://docs.rs/liquid/0.22.0/liquid/struct.ParserBuilder.html#method.partials).  See the [`partials` module](https://docs.rs/liquid/0.22.0/liquid/partials/index.html) for different policies you can implement.  The only baked-in `PartialSource` is in-memory but you can just as easily implement a filesystem source if you wish.

Note that Liquid is a fairly fragmented template language.  You have
- liquid-ruby's flavor
- Jekyll's flavor
- Shopify's flavor
- etc

This project is working towards conformance on liquid-ruby with Jekyll and Shopify conformance being implemented where it makes sense.

**Comment by stevensonmt** [comment]
Thanks for the help. I realized that handling partials was not a uniform spec of liquid after going through the source code a little more. Working on the best way to implement it for the project that led to the question. Cheers.
