### ISSUE TITLE
Should liquid use `time` instead of `chrono` ?

### ISSUE THREAD

**Issue by Geobert** [cobalt-org/liquid-rust#446]
With `chrono` slowly dying and `time` gaining traction, should liquid consider adopting `time` as well?

**Comment by epage** [comment]
Unsure as I haven't been keeping up on whats going on with these two crates

**Comment by Geobert** [comment]
https://www.reddit.com/r/rust/comments/qamgyh/is_the_chrono_crate_unmaintained/

Since, I think somebody as been approved to join de maintainers team, but the issue is still not fixed and I'm loosing confidence in this crate.

`time` has evolved a lot and can do many things `chrono` is doing and seems more maintained.

**Comment by VuiMuich** [comment]
Hi!
Do you have an estimate how big of an effort this move would be?

We are trying to replace `chrono` with `time` ourselves in [leftwm/leftwm](https://github.com/leftwm/leftwm) but we are getting panics, most probable due to conflicts by attempting to compile two versions of `time` into one binary.

I also agree that `chrono` looks not well with a ton of open PRs and the latest commit being last October :disappointed:

**Comment by epage** [comment]
I started playing around with `time`.  Maybe I missed it but I didn't see support for `%` format strings.  We **might** be able to port to `time` without it (can't remember if parsing that is exposed in important areas) but it'll take a lot more work.

**Comment by Geobert** [comment]
`time` use a different format to specify formats: `"[year]-[month]-[day] [hour]:[minute]:[second] [offset_hour sign:mandatory][offset_minute]"` is what you need :)

**Comment by epage** [comment]
I saw it supported that.  The problem is that it doesn't support the other format.  As I said, switching formats increases the porting work.   I also double checked and we do need a parser for the other format (e.g. [`date`](https://shopify.github.io/liquid/filters/date/)).

**Comment by VuiMuich** [comment]
And there is a `parse` crate feature; I haven't had a look at its mechanics yet, though.

**Comment by epage** [comment]
v0.24.0 is now released with this
