### ISSUE TITLE
Parser ignores value of BlockReflection::end_tag()

### ISSUE THREAD

**Issue by Kneelawk** [cobalt-org/liquid-rust#452]
# System Information
liquid-rust version: commit 5c9c4c06bd45fa89704f93bd320f27138da338f7

# The Issue
Currently all implemented block plugins have their tags in the format `<name>`-`end<name>` and it turns out that the liquid parser only supports tags block tags in this format. Attempting to implement a plugin block with tags in any other format results in unexpected behavior.

## Expected Behavior
Implementing a block tag with a `BlockReflection` implementation:
```rust
impl BlockReflection for CustomBlock {
    fn start_tag(&self) -> &str {
        "begincustom"
    }

    fn end_tag(&self) -> &str {
        "endcustom"
    }

    fn description(&self) -> &str {
        "description"
    }
}
```
would be expected to be able to parse the string `{% begincustom %}Hello Liquid!{% endcustom %}`.

## The Actual Behavior
The above implementation fails to parse the string `{% begincustom %}Hello Liquid!{% endcustom %}`, stating that `endcustom` is an unknown tag. However, it can parse the string `{% begincustom %}Hello Liquid!{% endbegincustom %}`, despite the `CustomBlock`'s `end_tag()` implementation returning `endcustom` instead of `endbegincustom`.

## As a Failing Unit Test
The test:
```rust
    #[test]
    fn test_custom_block_tags() {
        use crate::{BlockReflection, ParseBlock};
        use crate::error::ResultLiquidReplaceExt;
        use std::io::Write;

        #[derive(Debug, Default, Copy, Clone)]
        struct CustomBlock;
        #[derive(Debug)]
        struct Custom {
            inside: Template,
        }

        impl BlockReflection for CustomBlock {
            fn start_tag(&self) -> &str {
                "begincustom"
            }

            fn end_tag(&self) -> &str {
                "endcustom"
            }

            fn description(&self) -> &str {
                "I am a description"
            }
        }

        impl ParseBlock for CustomBlock {
            fn parse(
                &self,
                mut arguments: TagTokenIter,
                mut block: TagBlock,
                options: &Language,
            ) -> Result<Box<dyn Renderable>> {
                arguments.expect_nothing()?;

                let inside = block.parse_all(options).map(Template::new)?;

                Ok(Box::new(Custom { inside }))
            }

            fn reflection(&self) -> &dyn BlockReflection {
                self
            }
        }

        impl Renderable for Custom {
            fn render_to(&self, writer: &mut dyn Write, runtime: &dyn Runtime) -> Result<()> {
                write!(writer, "<pre>").replace("Failed to render")?;
                self.inside.render_to(writer, runtime)?;
                write!(writer, "</pre>").replace("Failed to render")?;

                Ok(())
            }
        }

        let mut options = Language::default();
        options
            .blocks
            .register(CustomBlock.start_tag().to_string(), Box::new(CustomBlock));

        let runtime = RuntimeBuilder::new().build();

        let text = "{% begincustom %}Hello Liquid!{% endcustom %}";
        let template = parse(text, &options).map(Template::new).unwrap();
        let output = template.render(&runtime).unwrap();

        assert_eq!(output, "<pre>Hello Liquid!</pre>");
    }
```
fails with the error:
```
called `Result::unwrap()` on an `Err` value: Error { inner: InnerError { msg: Owned(" --> 1:34\n  |\n1 | {% begincustom %}Hello Liquid!{% endcustom %}\n  |                                  ^-------^\n  |\n  = Unknown tag."), user_backtrace: [Trace { trace: None, context: [(Singleton("requested"), Inline("endcustom")), (Singleton("available tags"), Inline("")), (Singleton("available blocks"), Inline("begincustom"))] }], cause: None } }
```

# Potential Fix
Lines [294](https://github.com/cobalt-org/liquid-rust/blob/5c9c4c06bd45fa89704f93bd320f27138da338f7/crates/core/src/parser/parser.rs#L294) and [367](https://github.com/cobalt-org/liquid-rust/blob/5c9c4c06bd45fa89704f93bd320f27138da338f7/crates/core/src/parser/parser.rs#L367) of `crates/core/src/parser/parser.rs` are responsible for detecting end-tags in `TagBlock`. These make the assumption that the end-tag is will always be in the format `end<name>` where `<name>` is the value returned by the block's `BlockReflection::start_tag()`. This assumption is causing the unexpected behavior when interfacing with blocks with non-standard `BlockReflection::end_tag()` values.

If `TagBlock` were changed to keep track of both a block's start-tag and end-tag, using them in the correct situations, this unexpected behavior could be resolved.

# Pull Request
I am working on a pull request to fix this issue and will submit it shortly.

**Comment by epage** [comment]
Are diverging start/end tags supported in ruby liquid?  Is there precedence in it for it?

**Comment by Kneelawk** [comment]
Looking through the Liquid documentation, I cannot see any mechanism for registering a block not in the `<name>`-`end<name>` format. Blocks are registered with `Liquid::Template.register_tag("<name>", <tag-class>)` just like non-block tags. Perhaps it would make more sense to remove `BlockReflection::end_tag()` from the API?

My use-case for block tags not in the `<name>`-`end<name>` format are macro definition tags that can be either single-line (in which case the macro is defined as a filter-chain) or a block (in which case the macro is defined as the contents of the block). My original set of macro-definition tags had a tag called `define` that would define a single-line macro and ones called `begindef` and `enddef` for defining a block macro. I chose these names because it made it clear which tags were single-line and which were multi-line.

**Comment by epage** [comment]
The overall intention for `end_tag` was to open us up to simplifying the code like your PR did, we just never got around to doing it.   Looking over it, I'm tempted to merge #453.  My concern is whether we should enforce `end<something>` (and how) or not.

**Comment by Kneelawk** [comment]
One option is to have diverging start/end tags enabled by a feature flag. If the feature flag is enabled, then diverging start/end tags are supported like in #453. If the feature flag is disabled, then attempting to register a block plugin with diverging start/end tags causes a panic.

Otherwise, to me, it seems the clearest way to enforce `end<something>` block end tags is to just remove the `end_tag` method.

**Comment by epage** [comment]
Been thinking over this and looking over the Ruby code.  Technically, someone can override the `block_delimiter`. There is no place they explicitly say how blocks end.

Think I'll go forward with this.

**Comment by epage** [comment]
As far as I could tell, there was no breaking change with this (since using anything else for these fields would have been broken).

I've released liquid-core with this change since I'm assuming thats all that is needed for this.

**Comment by Kneelawk** [comment]
Sounds good. Thank you.
