### ISSUE TITLE
How to use the "Template" class.

### ISSUE THREAD

**Issue by iamtheblackunicorn** [cobalt-org/liquid-rust#456]
This is a general question: How would I use `liquid-rust` to insert a bunch of strings into a given template?
Your docs do not have any examples for this. As I understand it, one has to use the `Template` class. Help would be more than appreciated. And thank you for making this crate.

**Comment by epage** [comment]
I feel I'm missing something in your question, so I'll start with this and hopefully you can highlight where the mismatch in our understanding is.

In the  README, we provide this example
```rust
let template = liquid::ParserBuilder::with_stdlib()
    .build().unwrap()
    .parse("Liquid! {{num | minus: 2}}").unwrap();

let mut globals = liquid::object!({
    "num": 4f64
});

let output = template.render(&globals).unwrap();
assert_eq!(output, "Liquid! 2".to_string());
```

`"Liquid! {{num | minus: 2}}"` is the template

`globals` is what you'd use to define the strings you want your template to access.

**Comment by iamtheblackunicorn** [comment]
Thank you for clarifying this for me! My concrete use-case is this: I have a function that returns a `HashMap<String,String>` and has the contents of `"title":"My Site"` and I have a template with this line of Liquid in it: `<h1>{{ site.title }}</h1>`. How would I use the example you gave me to return this line, given the Liquid above and the `HashMap`: `<h1>My Site</h1>`? I would be much obliged if you could clear this up for me because, frankly, I'm a bit lost.

**Comment by epage** [comment]
It would be something approximately like:
```rust
let template = "<h1>{{ site.title }}</h1>.";
let vars: HashMap<String, String> = ...;

let template = liquid::ParserBuilder::with_stdlib()
    .build().unwrap()
    .parse(template).unwrap();

let mut globals = liquid::object!({
    "site": vars,
});

let output = template.render(&globals).unwrap();
assert_eq!(output, "<h1>My Site</h1>".to_string());
```
The main part I might not have the syntax right on is `globals`.  I don't remember if the macro supports accepting an arbitrary type like that.

This isn't the only way of initializing `globals` either.  `template.render` accepts an `ObjectView`   Other options look roughly like:
```rust
// Use the blanket `impl ObjectView for HashMap`
let mut globals: HashMap<String, &HashMap<String, String>> = HashMap::new();
globals.insert("site".into(), &vars);

// Use our derive
#[derive(liquid::ObjectView)]
struct Globals {
    site: &HashMap<String, String>,
}
let globals = Globals { site: &vars };
```
The last would be the most optimal.

**Comment by iamtheblackunicorn** [comment]
Thank you most kindly. If I have any questions, I'll come back here. 😉❤️

**Comment by iamtheblackunicorn** [comment]
> It would be something approximately like:
> 
> ```rust
> let template = "<h1>{{ site.title }}</h1>.";
> let vars: HashMap<String, String> = ...;
> 
> let template = liquid::ParserBuilder::with_stdlib()
>     .build().unwrap()
>     .parse(template).unwrap();
> 
> let mut globals = liquid::object!({
>     "site": vars,
> });
> 
> let output = template.render(&globals).unwrap();
> assert_eq!(output, "<h1>My Site</h1>".to_string());
> ```
> 
> The main part I might not have the syntax right on is `globals`. I don't remember if the macro supports accepting an arbitrary type like that.
> 
> This isn't the only way of initializing `globals` either. `template.render` accepts an `ObjectView` Other options look roughly like:
> 
> ```rust
> // Use the blanket `impl ObjectView for HashMap`
> let mut globals: HashMap<String, &HashMap<String, String>> = HashMap::new();
> globals.insert("site".into(), &vars);
> 
> // Use our derive
> #[derive(liquid::ObjectView)]
> struct Globals {
>     site: &HashMap<String, String>,
> }
> let globals = Globals { site: &vars };
> ```
> 
> The last would be the most optimal.

Just tested this, turns out it works brilliantly.

Here's a function for that:

```rust
use std::fs;
use liquid::Parser;
use liquid::ParserBuilder;
use std::collections::HashMap;

fn read_file(file:String) -> String {
    let contents = fs::read_to_string(file)
        .expect("I/O failed.");
    return contents;
}

fn fill_template(template: String, content: HashMap<String, String>, scope_name: String) -> String {
    let liquid_string = read_file(template);
    let scoped_vars: HashMap<String, String> = content;
    let template = liquid::ParserBuilder::with_stdlib()
        .build().unwrap()
        .parse(&liquid_string).unwrap();
    let mut globals = liquid::object!({
        scope_name: scoped_vars
    });
    let output = template.render(&globals).unwrap();
    return output;
}

fn test_template_filler(){
    let template_file: String = String::from("template.html");
    let scope_name: String = String::from("page");
    let mut content: HashMap<String, String> = HashMap::new();
    content.insert(String::from("title"), String::from("Hello World!"));
    content.insert(String::from("description"), String::from("This is a welcome post."));
    content.insert(String::from("content"), String::from("Lreom ipsum sit dolor amet. Lorem ipsum sit dolor amet."));
    let compiled_code: String = fill_template(template_file, content, scope_name);
    println!("{:?}", compiled_code);
}

fn main(){
    test_template_filler();
}
```

And the Liquid template:

```liquid
<!DOCTYPE html>
<html>
 <head>
  <title>{{ page.title }}</title>
 </head>
 <body>
  <h1>{{ page.title }}</h1>
  <p>{{ page.description }}</p>
  <hr/>
  <p>{{ page.content }}</p>
 </body>
</html>
```

**Comment by iamtheblackunicorn** [comment]
Hi! Following problem:

I have this template here:
```liquid
<!DOCTYPE html>
<html>
 <body>
 <hr/>
 {% for post in page.posts %}
 <h2>{{ post.title }}</h2>
 <p>{{ post.description }}</p>
 <p><a href="{{ post.url | prepend: site.baseurl }}">READ ME</a></p>
 <hr/>
 {% endfor %}
 </body>
</html>
```

and this `HashMap<String, HashMap<String, String>>`:

```JSON
{
  "2020-03-09-Welcome-Part-I": {
    "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
    "layout": "post",
    "title": "Part I of a Welcome!",
    "description": "The first part of a small welcome post!",
    "url": "posts/2020-03-09-Welcome-Part-I.html"
  },
  "2020-03-09-Welcome-Part-III": {
    "description": "The third part of a small welcome post!",
    "layout": "post",
    "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
    "title": "Part III of a Welcome!",
    "url": "posts/2020-03-09-Welcome-Part-III.html"
  },
  "2020-03-09-Welcome-Part-II": {
    "description": "The second part of a small welcome post!",
    "title": "Part II of a Welcome!",
    "layout": "post",
    "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
    "url": "posts/2020-03-09-Welcome-Part-II.html"
  }
}
```
that represents `page.posts`. My question to you is the following: How on earth do I put the data in the `HashMap` into the `for` loop? The code sample you gave me above doesn't work.

**Comment by iamtheblackunicorn** [comment]
For context: I'm building my own static-site generator and trying to generate the `index.html` from a template with the contents above.

**Comment by iamtheblackunicorn** [comment]
To have a look at what I'm *trying* to do here's the main file of the generator: [View](https://github.com/iamtheblackunicorn/acid/blob/main/src/main.rs) Builds fail around line 274. The `fill_template` is causing problems.

**Comment by epage** [comment]
I can't access that repo.

When you say "builds" fail, is that referring to Rust code or Liquid templates?

**Comment by epage** [comment]
Ok, I reproduced this with `liquid-bin`
context:
```json
{
  "site": {
    "baseurl": "foo"
  },
  "page": {
    "posts": {
      "2020-03-09-Welcome-Part-I": {
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "layout": "post",
        "title": "Part I of a Welcome!",
        "description": "The first part of a small welcome post!",
        "url": "posts/2020-03-09-Welcome-Part-I.html"
      },
      "2020-03-09-Welcome-Part-III": {
        "description": "The third part of a small welcome post!",
        "layout": "post",
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "title": "Part III of a Welcome!",
        "url": "posts/2020-03-09-Welcome-Part-III.html"
      },
      "2020-03-09-Welcome-Part-II": {
        "description": "The second part of a small welcome post!",
        "title": "Part II of a Welcome!",
        "layout": "post",
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "url": "posts/2020-03-09-Welcome-Part-II.html"
      }
    }
  }
}
```

Template
```liquid
{
  "site": {
    "baseurl": "foo"
  },
  "page": {
    "posts": {
      "2020-03-09-Welcome-Part-I": {
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "layout": "post",
        "title": "Part I of a Welcome!",
        "description": "The first part of a small welcome post!",
        "url": "posts/2020-03-09-Welcome-Part-I.html"
      },
      "2020-03-09-Welcome-Part-III": {
        "description": "The third part of a small welcome post!",
        "layout": "post",
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "title": "Part III of a Welcome!",
        "url": "posts/2020-03-09-Welcome-Part-III.html"
      },
      "2020-03-09-Welcome-Part-II": {
        "description": "The second part of a small welcome post!",
        "title": "Part II of a Welcome!",
        "layout": "post",
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "url": "posts/2020-03-09-Welcome-Part-II.html"
      }
    }
  }
}
```

When you look over a dict / hash/ map / object, you get an array of two elements, the key and the value.   So the change that was needed was to index into that array to get the value.

Liquid should have been providing an error message saying that the available indexes on `post` were `0..1`.  If you have ideas on improving the error message, they are welcome.

**Comment by iamtheblackunicorn** [comment]
Hi! Wow, thank you so much for your quick reply!! I do understand what you're saying, however, from what you said, I still have questions:

- My site configuration happens in a file called `config.json`. I read that file and then retrieve the data into a `HashMap<String,String>`. How would I fuse the configuration `HashMap<String,String>` with the posts `HashMap` which is of type `HashMap<String,HashMap<String,String>`?

- In the template, the `[1]` will allow me to iterate over all posts and render their corresponding variables foreach post?

- What is `liquid-bin`?

And yes, of course, I'll see what I can do for making that error message clearer after I've finished ***Acid***.❤️❤️ Thank you again for all your help!❣️

**Comment by epage** [comment]
> What is liquid-bin?

Its a CLI wrapper around liquid to allow for one-off testing in cases like this.

I ran `liquid-bin --context data.json --input template.liquid --output index.html`

> In the template, the [1] will allow me to iterate over all posts and render their corresponding variables foreach post?

Not sure if I understand the question.  Let me take a try

`post[0]` evaluates to `"2020-03-09-Welcome-Part-I"`

`post[1]` evaluates to
```json
{
        "content": "<h2 id='welcome!'>Welcome!</h2>\n\n<p>Lorem ipsum sit dolor amet. Lorem ipsum sit dolor amet.</p>\n",
        "layout": "post",
        "title": "Part I of a Welcome!",
        "description": "The first part of a small welcome post!",
        "url": "posts/2020-03-09-Welcome-Part-I.html"
      }
```

>  My site configuration happens in a file called config.json. I read that file and then retrieve the data into a HashMap<String,String>. How would I fuse the configuration HashMap<String,String> with the posts HashMap which is of type HashMap<String,HashMap<String,String>?

If you are starting to get into deeper object hierarchies like this, I'd recommend either
- Defining some structs and deriving the `ObjectView` trait on it.
- Using `liquid::Object` which allows arbitrarily deep objects and integrates with serde for loading it from files.

I've not pulled up the APIs in a bit but the `ObjectView` approach would look something like:
```rust
#[derive(liquid::ObjectView)]
struct Context {
    site: HashMap<String, String>
    pages: HashMap<String, HashMap<String, String>>,
}
```
Native rust types like this are not just easier and less error prone to work with, they should also be faster.

**Comment by iamtheblackunicorn** [comment]
Hi Ed! :heart:

Wow, thank you so much for your answer! I'm really sorry that I'm replying only now! But! To your answers:

- 1.) Ok, I suspected as much, just wanted to be sure! Thank you. :heart:
- 2.) Hmm, no my question was, how do I iterate over *all* posts and use the post's data (`post.title`, `post.content`, etc...) in the template? I'm currently working on [this project](https://github.com/iamtheblackunicorn/strawberrymilk) to integrate just such a functionality and I'm currently giving it a whirl. I'll try to figure it out by myself first! If I have problems, can I come back here and ask you for advice?
- 3.) That makes sense, I'm gonna look into this and see if I can use what you suggested!

Finally, thank you so much, for all your help!! I'm trying to write something similar to Jekyll and re-write my main two blogs using this new Rust app of my own. If you want to check them out, I can send you the links.

P.S.: I made the [Acid](https://github.com/iamtheblackunicorn/acid) project public. Maybe that clarifies my problem.

**Comment by iamtheblackunicorn** [comment]
@epage Hi, quick follow-up: Tried what you suggested using the `ObjectView` and got the following error:
```text
error[E0277]: the trait bound `Context: _ValueView` is not satisfied
   --> src/main.rs:198:10
    |
198 | #[derive(liquid::ObjectView)]
    |          ^^^^^^^^^^^^^^^^^^ the trait `_ValueView` is not implemented for `Context`
    |
note: required by a bound in `_ObjectView`
   --> /Users/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/liquid-core-0.24.1/src/model/object/mod.rs:20:23
    |
20  | pub trait ObjectView: ValueView {
    |                       ^^^^^^^^^ required by this bound in `_ObjectView`
    = note: this error originates in the derive macro `liquid::ObjectView` (in Nightly builds, run with -Z macro-backtrace for more info)
```
for [this project](https://github.com/iamtheblackunicorn/strawberrymilk). The lines that cause the error are from 221-236 and 198-202. What would you advise?

**Comment by iamtheblackunicorn** [comment]
It isn't that I do not understand the error, I'm juet wondering how to resolve it in such a way to get the results I want: To render the struct's contents in a template and by "inheriting" the `ObjectView` struct, at least as far as possible in Rust.

**Comment by epage** [comment]
You also need to derive `ValueView`

**Comment by iamtheblackunicorn** [comment]
Thank you so much!!! Turns out, I figured out what the problem was. Have a look at [this commit](https://github.com/iamtheblackunicorn/strawberrymilk/commit/0a0ca98ac23cf3c5321057b7562f77991a1ea4e6). Did I do it right? I'm going to use what I learned from the tests and my fix just now in [Acid](https://github.com/iamtheblackunicorn/Acid) and come back here if I have any problems! Thank you for all your help! :heart_on_fire:

**Comment by iamtheblackunicorn** [comment]
Hi @epage I have two last questions:

- What do you think of [Acid.rs](https://github.com/iamtheblackunicorn/acid)?

- How would I handle `include whatever.html` in a Liquid template? What would the directory structure look like and what structs/methods would I use?

**Comment by epage** [comment]
> How would I handle include whatever.html in a Liquid template? What would the directory structure look like and what structs/methods would I use?

You can see how cobalt does this
- https://github.com/cobalt-org/cobalt.rs/blob/master/src/cobalt_model/template.rs#L14
- https://cobalt-org.github.io/docs/directory/

We currently support a jekyll tag and a shopify tag for this.  The level of fidelity is not great; they need some re-work.  Shopify has recently replaced their old tag with a new one and we have not yet added support for it.

> What do you think of [Acid.rs](https://github.com/iamtheblackunicorn/acid)?

Congrats on getting your first release out!

Random observations as I go
- I'd recommend clap instead of doing CLI parsing yourself (and use subcommands instead of flags)
  - The [CLI book](https://rust-cli.github.io/book/index.html) probably has other good tips
- Other tools that might be useful
  - I don't think I've published these yet but cobalt has an `engarde` crate to help with formatting code fences and a `file_serve` crate for running a development server.  I could get these published if you'd like
  - trycmd or snapbox work well for testing!
- I'd recommend against json for config but to use something that supports comments and is more forgiving

**Comment by iamtheblackunicorn** [comment]
@epage Hi, sorry for the late response. :disappointed: 

- About including snippets: I had a look and I might implement this soon, just figruing out how. :thinking:
- Ad ***Acid***: Thank you so much for saying that and for your congratulations!!! Means a lot to me!! :heart:
   - I was considering using clap but I need to get a little more familiar with `clap` and some Rust constructs before I do implement that, actually.
   - I would really appreciate a crate with a simple function for serving a directory on `localhost`!!!
   - How do you mean "testing"? :see_no_evil:
   - No, I agree completely, I'm playing with the idea of using YAML or TOML in the next release.

All that being said, thank you so much for all your kind feedback, it means a lot to me and I'm really sorry again for responding so late.

**Comment by iamtheblackunicorn** [comment]
Playing around with `file_serve`:

```rust
use std::path::PathBuf;
use file_serve::Server;

fn serve_dir(src: String) {
    let mut path = PathBuf::new();
    path.push(src);
    let server_instance: Server = Server::new(path);
    server_instance.serve();
}

fn main(){
    serve_dir(String::from("pages"));
}
```

On which port of `localhost` is the directory being served?

**Comment by iamtheblackunicorn** [comment]
So how would I retrieve it?

**Comment by iamtheblackunicorn** [comment]
@epage No, you've done enough, I'll write it up, already working on a generic function to handle all that stuff. I would ask you one thing, however: Once I'm done, could you post the example I'm going to post here, once I've finished, into the docs of `file-serve`, so that others have it a bit easier? And thank you again so much!! I was going crazy yesterday. :heart:

**Comment by iamtheblackunicorn** [comment]
Here you go:

```rust
use std::path::PathBuf;
use file_serve::Server;

/// Starts a web server at "addr" for "path".
fn serve_dir_example(path: String) {
    let mut path: PathBuf = PathBuf::new();
    path.push(path);
    let server_instance: Server = Server::new(path);
    let address: String = server_instance.addr();
    server_instance.serve();
}
```

**Comment by iamtheblackunicorn** [comment]
@epage Brilliant, thanks! You can view the changes I made to ***Acid*** [here](https://github.com/iamtheblackunicorn/acid/commit/3efb0b8220eb6e0f3ef88057ae220a51cd04bf91). :heart_on_fire:

**Comment by iamtheblackunicorn** [comment]
Still to do:

- [ ] Rewrite the config file format.
- [ ] Add `clap` into the mix.
- [ ] Fix [acid-tripping](https://github.com/iamtheblackunicorn/acid-tripping)
