### ISSUE TITLE
Allow accessing renderer state/runtime before rendering

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [cobalt-org/liquid-rust#458]
I am using liquid in a way where rendering certain custom tags updates a global variable. The way I implemented this right now is very unsafe so I want to instead pass a copy or mutable reference of this variable to the liquid renderer, have the custom tag update it in the render step and then (if required) overwrite the original variable when rendering is finished.

From what I can tell, this isn't possible at the moment. `liquid_core` has a [Template](https://docs.rs/liquid-core/latest/liquid_core/struct.Template.html) struct that is different from the [Template](https://docs.rs/liquid/latest/liquid/struct.Template.html) in the `liquid` crate and should allow me to pass in my own `Runtime` with pre-set registers, but I don't know how to instantiate it.

Any help would be greatly appreciated.

**Comment by epage** [comment]
Is this a Rust variable or a Liquid variable?

**Comment by HoLLy-HaCKeR** [comment]
It's a complex rust struct that can contain HashSets, my own structs, etc.

**Comment by epage** [comment]
Thanks.  Got some more questions to try to understand the need and how we might be able to fill it.

Is the data coupled to the specific `render` call?  Or are you needing to know when each `render` call starts and ends?  If neither, would it work to pas this into your tag's constructor as an `Arc<Mutex<T>>`?  

Even if its just knowing the start/end of each render call, we can look into options of telling tags when we are starting a new render.  Granted, there are threading issues with this and if you are rendering from multiple threads, then you might need to rely on TLS or thread ids.

Also, could you expand on the use case?  Why is the rust code and the termplate needing to interact like this?

**Comment by HoLLy-HaCKeR** [comment]
I'm using liquid as the templating system for a content-first story engine and I have some custom tags/blocks for very basic operations such as checking or setting variables. These operations happen inside the liquid content since they're very tied to the story. More complex operations happen through a scripting language.

I'm running from wasm so everything is single-threaded. I just look up the liquid template, parse it, pass it some globals and then render it. After rendering I want it to have updated some data based on what the template contained.

My initial idea was be use the [Registers](https://docs.rs/liquid-core/latest/liquid_core/runtime/struct.Registers.html) struct to pass in a reference (or `Rc<RefCell<T>>`, or multi-threaded equivalent) which my tags can access and update. Passing in a full copy of the data and extracting it after rendering would be fine too.

Is this more clear? I understand my usecase may not be the typical one for liquid, but it's the best tool I found for the job that doesn't involve writing my own templating engine.

**Comment by epage** [comment]
Wow, that is a fun use case!  That definitely helps understand the requirements for your use case.

So far the focus has been on more mundane cases where you you want to avoid rendering being stateful because that'd lead to bugs.

Its been a while since I've look at this part of liquid but I think registers can make sense for how we could allow this longer term.

One short term option is to pass the `Rc<RefCell<T>>` into your tag before passing your tag to liquid.  This does mean you'd have the same state for the lifetime of your `Parser` and `Template`.  It **sounds** like that might work for you but you'd know best.  I actually wonder if this is better than registers.

**Comment by HoLLy-HaCKeR** [comment]
I just did a quick test and passing to the tags constructor seems to work! I need to use `Arc<Mutex<MyState>>` because tags are required to be `Send+Sync`, but the performance difference is negligible in my usecase. That solves my issue :)

I'll close this issue for now but feel free to re-open it if you want to track a change related to it (such as exposing `Registers`). Thanks for the help!
