### ISSUE TITLE
with_time unimplemented

### ISSUE THREAD

**Issue by djwf** [cobalt-org/liquid-rust#465]
As discussed in #252, the `with_time` method is unimplemented (always returns `Nil`).

Discussion about implementing that method, and other fixes required to do so, belong here.

**Comment by djwf** [comment]
It turns out that our DateTime implementation does not handle dates and times without offsets, so we'll need another issue for that.

**Comment by epage** [comment]
See https://github.com/cobalt-org/liquid-rust/issues/48

**Comment by djwf** [comment]
Fixed by #466
