### ISSUE TITLE
could not compile kstring

### ISSUE THREAD

**Issue by eighty4** [cobalt-org/liquid-rust#470]
liquid-rust version: 0.26.0
rust version: 0.1.6
OS: mac 12.3.1

Upgrading from 0.25.0 to 0.26.0 gives me the following error:

```
error: `MaybeUninit::<T>::assume_init` is not yet stable as a const fn
   --> /Users/adam/.cargo/registry/src/github.com-1ecc6299db9ec823/kstring-2.0.0/src/string.rs:844:17
    |
844 |                 std::mem::MaybeUninit::uninit().assume_init()
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `kstring` due to previous error
```

I didn't see any relevant issues on kstring or liquid-rust.

**Comment by epage** [comment]
kstring's MSRV is 1.59.0 which is when support for this function in `const` contexts was added.  liquid's MSRV was updated accordingly.
