### ISSUE TITLE
Render Tag

### ISSUE THREAD

**Issue by YuiYukihira** [cobalt-org/liquid-rust#471]
Hi, sorry if this is a misunderstanding on my part.

But looking [online](https://shopify.github.io/liquid/tags/template/#include), the "include" tag is deprecated and the [render](https://shopify.github.io/liquid/tags/template/#render) tag should be used instead.

I was wondering what the status of this is and if there is any intention to add the new tag? Thanks

**Comment by epage** [comment]
Yes, we need to resolve #419 and close the gap on that.  Unfortunately, a lot of my attention is elsewhere atm so I'm not getting to spend as much time on liquid as I would like

**Comment by YuiYukihira** [comment]
Thanks for confirming this for me. Would you be willing to accept a PR for the render tag if I were to make one?
