### ISSUE TITLE
[Idea] Liquid Rendering Performance Optimization

### ISSUE THREAD

**Issue by amourjun** [cobalt-org/liquid-rust#557]
In response to the phenomenon of CPU resource consumption due to services rendering on the AST of liquid, in order to improve the performance of SSR, can we preprocess the liquid file in advance in the database, parsing it into a form of data that can be more efficiently executed, so that we can focus on dynamically rendering and loading the data when a user request comes in, without having to repeat the execution of the static fixed logic.

Of course, the liquid rendering process itself changes based on dynamic data loading, but I'm sure there would still be redundant computational logic occurring in this scenario, and this implementation would be more difficult.

I'm not sure if anyone has any suggestions on this idea, please give advice, it's greatly appreciated!

**Comment by epage** [comment]
Sounds like this would require serializing an deserializing the parsed form, correct?  In #312 I bring up the idea of byte code.  The big problem with any such design is that liquid is a very dynamic format when it comes to plugins and being able to track plugin state and have it be compatible across runs would be a big issue.

**Comment by amourjun** [comment]
Hi @epage 
Indeed you are right, like the idea you mentioned in #312, bytecode can be a more efficient use of cpu resources to execute liquid.

The plugins you mentioned and any dynamic formats are particularly challenging on this topic, to avoid it my idea is to go for serialization against static formats, but how to zone the proper distinction between dynamic and static content is a task that needs to be prepared well in advance.

Pessimistically, I think most of the performance bottleneck for a high degree-of-freedom dynamic format like liuquid should be in the dynamic format rendering process, and serializing only for static formats, as well as doing non-reusable serialization for dynamic formats, will not result in a very effective performance improvement.
