### ISSUE TITLE
Allow github actions to run on branches other than `master`

### ISSUE THREAD

**Issue by szabgab** [cobalt-org/liquid-rust#567]
I just tried to contribute some changes. I created a fork, enabled GitHub Actions in my fork, created a branch in my clone and pushed it out to my fork. Unfortunately the CI does not run there as it is currently restricted to master. So I can only benefit from the CI once I create the pull-request. If this is my first PR then I have to wait till someone approves the run.

It would be better if the CI was allowed to run on all branches. (in the `.github/workflows/*` files)

**Comment by epage** [comment]
Thanks for contributing!

I can understand wanting feedback before the first PR is approved.  Expanding the branches covered is an interesting idea.  The downside to doing that is that it can cause duplicate CI runs which can eat into the max number of parallel runners that is allowed within the org the job is running in.  That might be ok within your user account but doesn't work as well with ours or other users.  That duplicate run can also cause more email noise.

Not idea but you could make a PR against your own "master".  I wish github would allow us to only require PR approval if worksflows are touched.  Unsure if there is another route to help in this situation.  At least second+ time contributors don't have this issue.

**Comment by szabgab** [comment]
If I understand you correctly you would like to avoid running the CI as the org members use branches in the repositories of the organization.

Then maybe you could allow the jobs to run for `master` and any branch called /pr/* then suggest to all the contributors to use a branch called `pr/SOMETHING`.  I tried to demo what I suggest: https://github.com/szabgab/github-actions-for-pr-branches. That way your org members could still use any branch-name locally.

**Comment by epage** [comment]
Personally, I don't put branches in the org.  I was referring to whatever org the branch is coming from.  If I make the branch under my user (`epage`) then it will eat into my max concurrent runners within `epage`.

As this is only a problem for first time contributors, the impact seems relatively small (running `cargo test` will give most of the feedback you need), and the solutions don't sound great in my opinion, I'm going to go ahead and close this.
