### ISSUE TITLE
`round` filter should accept an optional "number of decimal places" argument

### ISSUE THREAD

**Issue by kennytm** [cobalt-org/liquid-rust#89]
[According to documentation](https://shopify.github.io/liquid/filters/round/), `round` filter accepts an optional argument, the number of decimal places to round to

```
{{ 183.357 | round: 2 }}
⇒ 183.36
```

As of 0.9.1, this argument is ignored and the above is incorrectly rounded to `183`.

**Comment by epage** [comment]
Thanks for reporting this.

Hopefully we'll be able to round and return a float.  My concern is we round the float but it still renders with `.0000001` which might expose a problem with using enums rather always converting to/from strings.

**Comment by epage** [comment]
Another, probably less performant, way of handling ints vs floats is the decimal module: https://crates.io/crates/decimal
