### ISSUE TITLE
Support for named arguments in filters

### ISSUE THREAD

**Issue by gmalette** [cobalt-org/liquid-rust#92]
Depends on #301 

Shopify/liquid supports named arguments for filters. 

[Example](https://help.shopify.com/themes/liquid/filters/additional-filters#default_pagination)

```liquid
{{ paginate | default_pagination: next: 'Older', previous: 'Newer' }}
```

Is this something liquid-rust aims to support? If yes, I'd be happy to make a PR for this; I already have part of a PR.

**Comment by epage** [comment]
Yup, we should be aiming for 100% compatibility with liquid.

**Comment by gmalette** [comment]
Awesome! I'll get this going!

**Comment by gmalette** [comment]
> 100% compatibility with liquid.

When you say 100%, do you mean 100% of the intended features, or 100% of even the unintended ones? Shopify/liquid is a minefield of weird behaviour; IIRC `a[b[c]]` gets interpreted as `a[b][c]`, for example.

**Comment by epage** [comment]
>  IIRC a[b[c]] gets interpreted as a[b][c], for example.

*sigh*

> When you say 100%, do you mean 100% of the intended features, or 100% of even the unintended ones? 

I'd say compatible with the interface but sometimes its hard to tell what behavior is intentional or incidental and undefined.

For example, how much of the [loose behavior I copied from Shopify](https://github.com/cobalt-org/liquid-rust/commit/ebd7ebc696b6176e6a8f24b3efb58f5683d1c341) is intentional or not?

**Comment by epage** [comment]
In #95, I'm introducing a `FilterValue` trait (from being just an `Fn`).  My thought is that this trait would get a `required` and `optional` functions that return param names in-order.  We can use this to centralize validation logic but also have liquid's interpreter process the name arguments and get them in a format that is easier to consume for filters (rather then every filter reinventing this or having to call a shared function we'd effectively have to make `pub` just so its feasible to implement filters correctly).
